IBU-10830
ProteinsWebTeam/interpro7-dw pull request #58
Opened 2024-03-04 08:41 UTC by HobnobMancer

[Jira](https://www.ebi.ac.uk/panda/jira/browse/IBU-10830)

## Update release workflow: `interpro.xml`

* Add `is-llm` and `is-llm-reviewed` attributes to XML output.
* Add `is-llm` and `is-llm-reviewed` child nodes to abstract attribute.
    * `is-llm` set to true if at least one description is ai-generated
    * `is-llm-reviewed` set to true if all ai-generated abstracts are reviewed

### Marked as draft

Need to fix existing `AttributeError` in `xmlfiles.py`:

```bash
Traceback (most recent call last):
  File "...interpro7-dw/interpro7dw/interpro/ftp/run.py", line 4, in <module>
    export_interpro(
  File "...interpro7-dw/interpro7dw/interpro/ftp/xmlfiles.py", line 447, in export_interpro
    elem.writexml(fh, addindent="  ", newl="\n")
  File "...python3.11/xml/dom/minidom.py", line 897, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "...python3.11/xml/dom/minidom.py", line 897, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "...python3.11/xml/dom/minidom.py", line 886, in writexml
    _write_data(writer, attrs[a_name].value)
  File "...python3.11/xml/dom/minidom.py", line 306, in _write_data
    data = data.replace("&", "&amp;").replace("<", "&lt;"). \
           ^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'replace'
```

2024-03-11 19:21 UTC, matthiasblum requested changes
I added a few suggestions.
You'll also need to change the target branch to `dev` (there will be conflicts, feel free to have a look but if you're unsure, let me know and I'll resolve them).
Thanks :)

2024-03-11 19:21 UTC, matthiasblum commented on interpro7dw/interpro/ftp/xmlfiles.py
> +
Just add attributes to the `abstract` element:

```suggestion
                abstract.setAttribute("is-llm", ab_is_llm)
                abstract.setAttribute("is-llm-reviewed", ab_is_rev_llm)
                elem.appendChild(abstract)

```

2024-03-14 12:10 UTC, matthiasblum commented on interpro7dw/interpro/ftp/xmlfiles.py
> +                    ab_is_reviewed_llm = "true"
Fix `NameError`:

```suggestion
                abstract.setAttribute("is-llm-reviewed", ab_is_reviewed_llm)
```

2024-03-14 12:10 UTC, matthiasblum commented on interpro7dw/interpro/ftp/xmlfiles.py
> +                abstract.setAttribute("is-llm-reviewed", ab_is_rev_llm)
Fix `NameError`:

```suggestion
                abstract.setAttribute("is-llm-reviewed", ab_is_reviewed_llm)
```

2024-03-14 13:59 UTC, HobnobMancer commented
Tested, and XML file generated successfully and correctly.

2024-03-14 17:51 UTC, merged